/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    'AppHeader.ce': typeof import('./src/components/feature/AppHeader/AppHeader.ce.vue')['default']
    AppNavigation: typeof import('./src/components/feature/AppNavigation/AppNavigation.vue')['default']
    BrandLogo: typeof import('./src/components/pure/BrandLogo/BrandLogo.vue')['default']
    ChangeLogTrigger: typeof import('./src/components/feature/ChangeLogTrigger/ChangeLogTrigger.vue')['default']
    DocsMenu: typeof import('./src/components/feature/DocsMenu/DocsMenu.vue')['default']
    DotMenu: typeof import('./src/components/feature/DotMenu/DotMenu.vue')['default']
    DotMenuLink: typeof import('./src/components/feature/DotMenu/DotMenuLink.vue')['default']
    IconNineDot: typeof import('./src/components/pure/IconNineDot/IconNineDot.vue')['default']
    IconsBrand: typeof import('./src/components/pure/IconsBrand/IconsBrand.vue')['default']
    IconsDotMenu: typeof import('./src/components/pure/IconsDotMenu/IconsDotMenu.vue')['default']
    IconsUserMenu: typeof import('./src/components/pure/IconsUserMenu/IconsUserMenu.vue')['default']
    UserAvatar: typeof import('./src/components/feature/UserAvatar/UserAvatar.vue')['default']
    UserMenu: typeof import('./src/components/feature/UserMenu/UserMenu.vue')['default']
    UserMenuEntry: typeof import('./src/components/feature/UserMenu/UserMenuEntry.vue')['default']
  }
}
